language: node_js
node_js:
- '8'
env:
  global:
  - BASE_URL: https://api.ratebeer.com/v1/api/graphql
  - secure: N5jnZoHaubj0EI742nwfl7wX5Qsw8qjh47zXQkXWgppbiBzPyJKZt3+vYtq3DQbTuwjNeOp5p69iM3Ker1yTVEm73K+Kv7mjOlysvmLEktFvLUCkfyzzoIT4BV9gYs5CP/RhVljTarnqTLhi5nx/3ReRT9ddn7V64AhHEIJjUXMa3vdFaQHCCPCNaw2JvGnTimpWlJCmVa13B5xfsv9ISwdkaM61UWevDe0wI/XatWV/7jzQ0ERL8HpcDsLjc6WLFKeFdLBntZHF9q8M9GVG4XAJq1fXTqZ7AQjejnicIjZRGUiyiQvoIK5pTMk1aqwdCMclpP3y7sHfk6px6lt4+imaX9NswJWQObOE1r3TEnZU2zDTAfIXROkgBQB8CFmuGUlFqOFHGxVtqQX/vmsB5O7PFUTzPTmDDqjkcwVf7N8gqlJppdmKoSA6H2RozbNI2EwEMNejMO91jDtay35JIhAhKDqsQ8OcIrFpyFCnw/8btGmTLRL20ZyhsmCBhoY0orGMosIj4PNmCT8alpLXgoX5GhYJOsizke0V9Hr1f6uIliOiYJiClBvIG8U1jIK0SNurvt52feTdaHxpEZ953qbZZvAkf0beAosiqDh1wuBW6SgYNoJZpK3NEdXQCOuQNbiiQqVvNL/FFeBY9raXQWz0cisy0n4QupNYz+fqQfA=
cache:
  directories:
  - node_modules
branches:
  only:
  - master
install:
- yarn install
- yarn run generate:gh-pages
script:
- echo "Skipping tests"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_ACCESS_TOKEN"
  target-branch: gh-pages
  local-dir: dist
  on:
    branch: master
